let assert = require("./assert.js")
let isNumber = require("./is-number.js")
let isUndefined = require("./is-undefined.js")
let vectorize = require("./vectorize.js")

let floor = vectorize(function(x){
  try {
    return Math.floor(x)
  } catch(e) {
    return NaN
  }
})

module.exports = floor

// tests
if (!module.parent && typeof(window) === "undefined"){
  let random = require("./random.js")
  let zeros = require("./zeros.js")

  let x = 5.95
  let yTrue = 5
  let yPred = floor(x)
  assert(yTrue === yPred, `floor(${x}) should be ${yTrue}, but instead was ${yPred}!`)

  x = -3.25
  yTrue = -4
  yPred = floor(x)
  assert(yTrue === yPred, `floor(${x}) should be ${yTrue}, but instead was ${yPred}!`)

  x = [1.25, 2.5, 3.75]
  yTrue = [1, 2, 3]
  yPred = floor(x)
  for (let i=0; i<yTrue.length; i++) assert(yTrue[i] === yPred[i], `floor(${x[i]}) should be ${yTrue[i]}, but instead was ${yPred[i]}!`)

  x = random([500])
  yTrue = zeros([500])
  yPred = floor(x)
  for (let i=0; i<yTrue.length; i++) assert(yTrue[i] === yPred[i], `floor(${x[i]}) should be ${yTrue[i]}, but instead was ${yPred[i]}!`)

  let hasFailed

  try {
    hasFailed = false
    floor("foo")
  } catch(e){
    hasFailed = true
  }

  assert(hasFailed, `floor("foo") should have failed!`)

  try {
    hasFailed = false
    floor({})
  } catch(e){
    hasFailed = true
  }

  assert(hasFailed, `floor({}) should have failed!`)

  try {
    hasFailed = false
    floor([1, 2, "three"])
  } catch(e){
    hasFailed = true
  }

  assert(hasFailed, `floor([1, 2, "three"]) should have failed!`)

  try {
    let foo
    hasFailed = false
    floor(foo)
  } catch(e){
    hasFailed = true
  }

  assert(hasFailed, `floor(foo) should have failed!`)

  try {
    hasFailed = false
    floor(() => {})
  } catch(e){
    hasFailed = true
  }

  assert(hasFailed, `floor(() => {}) should have failed!`)

  console.log("All tests passed!")
}
